#!/bin/sh
# v 1.1
# very simple script file to configure PBS client
# 
# set -xv

PBS_HOME=/var/spool/pbs
SBIN_PATH=/usr/sbin
HOST_NAME=`hostname`
DATE=`date +%d-%m-20%y`
domainname=`domainname`
INPUT="$1"

# prepare file on client node
prepare_client() {
echo " - Stopping pbs_mom service"
service pbs_mom stop
echo " - Configuration of servername file "
echo -ne "   |- using:" ${INPUT}
echo ${INPUT} > ${PBS_HOME}/server_name
echo
echo " - Backup of previous config file"
cp -f ${PBS_HOME}/mom_priv/config ${PBS_HOME}/mom_priv/config.sauv-${DATE}
sed -e 's/^\$clienthost.*/\$clienthost '${INPUT}'/' ${PBS_HOME}/mom_priv/config.sauv-${DATE} > ${PBS_HOME}/mom_priv/config.tmp
sed -e 's/^\$restricted.*/\$restricted \*\.'${domainname}'/' ${PBS_HOME}/mom_priv/config.tmp > ${PBS_HOME}/mom_priv/config
rm -rf ${PBS_HOME}/mom_priv/config.tmp
}

adjust_xpbs() {
echo " - Adjusting xpbsmon environement"
perl -pi -e "s/\*sitesInfo:.*/\*sitesInfo:  \{Local\;ICON\;$1\;$1\;$1\;MOM\;\{\{\( \( totmem \- availmem \) \/ totmem \) \* 100\} \{Memory Usage\:\} SCALE\} \{\{\( loadave \/ ncpus \) \* 100\} \{Cpu Usage\:\} SCALE\} \{nusers \{Number of Users\:\} TEXT\}\}/g" TCL_SITELIB/xpbsmon/xpbsmonrc

echo " - Adjusting xpbs environement"           
perl -pi -e "s/^\*serverHosts:.*/\*serverHosts: $1/" TCL_SITELIB/xpbs/xpbsrc
perl -pi -e "s/^\*selectHosts:.*/\*selectHosts: $1/" TCL_SITELIB/xpbs/xpbsrc
}

# start pbs_mom service
start_service() {
service pbs_mom start
}

##############################################
# main program
##############################################
if [ -z "$1" ]; then
	echo
	echo " Usage $0 name_of_server_pbs"
	else
	prepare_client
	adjust_xpbs $1
	start_service
fi
