#!/bin/sh
pbs_server_home=/var/spool/pbs

echo "lancement Xterm Log des servers"

if [ -d "${pbs_server_home}/server_logs" ]; then
	xterm -g 110x12+0 -fg blue -reverse -title ServerLogs -e tail -f /var/spool/pbs/server_logs/* &
	else 
	echo "pas de Server PBS"
fi
if [ -d "${pbs_server_home}/mom_logs" ]; then
	xterm -g 110x12+203 -fg green -reverse -title Momlogs -e tail -f /var/spool/pbs/mom_logs/* &
	else
	echo "pas de Mom Server"
fi
if [ -d "${pbs_server_home}/sched_logs" ]; then	
	xterm -g 110x12+405 -fg magenta -reverse -title SchedLogs -e tail -f /var/spool/pbs/sched_logs/* &
	else
	echo "pas de Sched Server"
fi
